# ***API (Application Programming Interface)***

Vivimos en un mundo donde todos están interconectados entre ellos, donde en pocos segundos conseguimos mandar un mensaje a una persona que está incluso a miles de kilómetros y donde, cómodamente desde la cama con nuestro smartphone, podríamos incluso programar encender la máquina del café; pero ¿cómo ocurre esta conexión?

¿Cómo permiten esto los diferentes dispositivos (tablet, pc, smartphone) y las aplicaciones? 

Concretamente, ¿cómo conseguimos hacer todas estas operaciones?

El héroe silencioso y poco citado que te permite hacer todo esto son las Application Programming Interface o mejor conocidas como API.

![API]()

Las APIs (Application Programming Interfaces) son un conjunto de reglas y protocolos que permiten la comunicación entre diferentes aplicaciones y sistemas. Las APIs facilitan la obtención y el intercambio de información entre aplicaciones sin necesidad de conocer los detalles de implementación de cada una de ellas.

![API](https://blog.finerioconnect.com/wp-content/uploads/2020/04/como-funciona-una-api.jpg)

![API](https://media.geeksforgeeks.org/wp-content/uploads/20230216170349/What-is-an-API.png)

## API y las API REST

Por lo general, la API sigue el formato de aplicación a aplicación, mientras que REST (Representational State Transfer que podríamos traducir como transferencia del estado) sigue una estructura diferente: Cliente-Servidor. El cliente y el servidor están evolucionando de forma independiente, proporcionando más flexibilidad en el trabajo.

API de aplicación a aplicación:
Cuando nos referimos a una API en general, nos referimos a un conjunto de reglas y protocolos que permiten la comunicación entre diferentes aplicaciones. En este caso, la comunicación es de aplicación a aplicación, lo que significa que una aplicación solicita información o servicios a otra aplicación.

Un ejemplo de API de aplicación a aplicación es la API de Twitter. Esta API permite a los desarrolladores interactuar con la plataforma de Twitter para realizar acciones como publicar tweets, acceder a tweets publicados, buscar usuarios, entre otros. En este caso, una aplicación (por ejemplo, una aplicación de análisis de redes sociales) se comunica directamente con la aplicación de Twitter a través de su API.



Arquitectura REST (Cliente-Servidor):
REST (Representational State Transfer) es un estilo de arquitectura que se utiliza comúnmente en la implementación de servicios web. En una arquitectura REST, se sigue un patrón de Cliente-Servidor. El cliente (generalmente una aplicación web, móvil o de escritorio) realiza solicitudes a un servidor que proporciona recursos y servicios. El cliente y el servidor evolucionan de forma independiente, lo que permite mayor flexibilidad en el desarrollo y mantenimiento de cada uno de ellos.

Un ejemplo de arquitectura REST es la API de OpenWeatherMap. OpenWeatherMap proporciona datos meteorológicos a través de una API RESTful. Un cliente (por ejemplo, una aplicación móvil del tiempo) realiza solicitudes a la API de OpenWeatherMap utilizando el protocolo HTTP, y el servidor de OpenWeatherMap responde con los datos meteorológicos solicitados.

_________

Para interactuar con una API, generalmente necesitarás realizar solicitudes HTTP. Python tiene una biblioteca popular llamada requests que facilita la realización de solicitudes HTTP. Primero, asegúrate de instalar la biblioteca requests ejecutando:

In [1]:
# !pip install requests

Para realizar una solicitud HTTP, puedes utilizar los métodos proporcionados por requests, como ``get``, ``post``, ``put`` y ``delete``. Por ejemplo, si deseas obtener datos de una API mediante una solicitud ``GET``, puedes hacer lo siguiente:

``MÉTODO POST``

Se usa comúnmente para comunicar al servidor la finalización de una operación específica, por ejemplo, para activar el desencadenador de otros scripts. Si es necesario, puede contener un paquete de información para pasar al servidor.

A menudo se usa mucho en lugar del método PUT para actualizar datos.

``MÉTODO GET``

Es el método que el buscador aplica de default para cada una de nuestras peticiones, para entendernos, cuando navegamos en un sitio web o hacemos clic en un enlace estamos efectuando una GET hacia ese recurso.

``MÉTODO PUT``

Según los principios REST tendría que ser usado para crear o actualizar un dato. Por ejemplo si llamáramos PUT/blog/artículo-2 estamos comunicando al server querer crear un nuevo artículo, llamado artículo-2.

``MÉTODO DELETE``

Es el contrario del PUT, se invoca cuando desea eliminar un recurso del servidor.

In [11]:
import json
import requests

response = requests.get("https://jsonplaceholder.typicode.com/todos")
response

In [13]:
todos = json.loads(response.text)
print(todos)

[{'userId': 1, 'id': 1, 'title': 'delectus aut autem', 'completed': False}, {'userId': 1, 'id': 2, 'title': 'quis ut nam facilis et officia qui', 'completed': False}, {'userId': 1, 'id': 3, 'title': 'fugiat veniam minus', 'completed': False}, {'userId': 1, 'id': 4, 'title': 'et porro tempora', 'completed': True}, {'userId': 1, 'id': 5, 'title': 'laboriosam mollitia et enim quasi adipisci quia provident illum', 'completed': False}, {'userId': 1, 'id': 6, 'title': 'qui ullam ratione quibusdam voluptatem quia omnis', 'completed': False}, {'userId': 1, 'id': 7, 'title': 'illo expedita consequatur quia in', 'completed': False}, {'userId': 1, 'id': 8, 'title': 'quo adipisci enim quam ut ab', 'completed': True}, {'userId': 1, 'id': 9, 'title': 'molestiae perspiciatis ipsa', 'completed': False}, {'userId': 1, 'id': 10, 'title': 'illo est ratione doloremque quia maiores aut', 'completed': True}, {'userId': 1, 'id': 11, 'title': 'vero rerum temporibus dolor', 'completed': True}, {'userId': 1, 'id': 12, 'title': 'ipsa repellendus fugit nisi', 'completed': True}, {'userId': 1, 'id': 13, 'title': 'et doloremque nulla', 'completed': False}, {'userId': 1, 'id': 14, 'title': 'repellendus sunt dolores architecto voluptatum', 'completed': True}, {'userId': 1, 'id': 15, 'title': 'ab voluptatum amet voluptas', 'completed': True}, {'userId': 1, 'id': 16, 'title': 'accusamus eos facilis sint et aut voluptatem', 'completed': True}, {'userId': 1, 'id': 17, 'title': 'quo laboriosam deleniti aut qui', 'completed': True}, {'userId': 1, 'id': 18, 'title': 'dolorum est consequatur ea mollitia in culpa', 'completed': False}, {'userId': 1, 'id': 19, 'title': 'molestiae ipsa aut voluptatibus pariatur dolor nihil', 'completed': True}, {'userId': 1, 'id': 20, 'title': 'ullam nobis libero sapiente ad optio sint', 'completed': True}, {'userId': 2, 'id': 21, 'title': 'suscipit repellat esse quibusdam voluptatem incidunt', 'completed': False}, {'userId': 2, 'id': 22, 'title': 'distinctio vitae autem nihil ut molestias quo', 'completed': True}, {'userId': 2, 'id': 23, 'title': 'et itaque necessitatibus maxime molestiae qui quas velit', 'completed': False}, {'userId': 2, 'id': 24, 'title': 'adipisci non ad dicta qui amet quaerat doloribus ea', 'completed': False}, {'userId': 2, 'id': 25, 'title': 'voluptas quo tenetur perspiciatis explicabo natus', 'completed': True}, {'userId': 2, 'id': 26, 'title': 'aliquam aut quasi', 'completed': True}, {'userId': 2, 'id': 27, 'title': 'veritatis pariatur delectus', 'completed': True}, {'userId': 2, 'id': 28, 'title': 'nesciunt totam sit blanditiis sit', 'completed': False}, {'userId': 2, 'id': 29, 'title': 'laborum aut in quam', 'completed': False}, {'userId': 2, 'id': 30, 'title': 'nemo perspiciatis repellat ut dolor libero commodi blanditiis omnis', 'completed': True}, {'userId': 2, 'id': 31, 'title': 'repudiandae totam in est sint facere fuga', 'completed': False}, {'userId': 2, 'id': 32, 'title': 'earum doloribus ea doloremque quis', 'completed': False}, {'userId': 2, 'id': 33, 'title': 'sint sit aut vero', 'completed': False}, {'userId': 2, 'id': 34, 'title': 'porro aut necessitatibus eaque distinctio', 'completed': False}, {'userId': 2, 'id': 35, 'title': 'repellendus veritatis molestias dicta incidunt', 'completed': True}, {'userId': 2, 'id': 36, 'title': 'excepturi deleniti adipisci voluptatem et neque optio illum ad', 'completed': True}, {'userId': 2, 'id': 37, 'title': 'sunt cum tempora', 'completed': False}, {'userId': 2, 'id': 38, 'title': 'totam quia non', 'completed': False}, {'userId': 2, 'id': 39, 'title': 'doloremque quibusdam asperiores libero corrupti illum qui omnis', 'completed': False}, {'userId': 2, 'id': 40, 'title': 'totam atque quo nesciunt', 'completed': True}, {'userId': 3, 'id': 41, 'title': 'aliquid amet impedit consequatur aspernatur placeat eaque fugiat suscipit', 'completed': False}, {'userId': 3, 'id': 42, 'title': 'rerum perferendis error quia ut eveniet', 'completed': False}, {'userId': 3, 'id': 43, 'title': 'tempore ut sint quis recusandae', 'completed': True}, {'userId': 3, 'id': 44, 'title': 'cum debitis quis accusamus doloremque ipsa natus sapiente omnis', 'completed': True}, {'userId': 3, 'id': 45, 'title': 'velit soluta adipisci molestias reiciendis harum', 'completed': False}, {'userId': 3, 'id': 46, 'title': 'vel voluptatem repellat nihil placeat corporis', 'completed': False}, {'userId': 3, 'id': 47, 'title': 'nam qui rerum fugiat accusamus', 'completed': False}, {'userId': 3, 'id': 48, 'title': 'sit reprehenderit omnis quia', 'completed': False}, {'userId': 3, 'id': 49, 'title': 'ut necessitatibus aut maiores debitis officia blanditiis velit et', 'completed': False}, {'userId': 3, 'id': 50, 'title': 'cupiditate necessitatibus ullam aut quis dolor voluptate', 'completed': True}, {'userId': 3, 'id': 51, 'title': 'distinctio exercitationem ab doloribus', 'completed': False}, {'userId': 3, 'id': 52, 'title': 'nesciunt dolorum quis recusandae ad pariatur ratione', 'completed': False}, {'userId': 3, 'id': 53, 'title': 'qui labore est occaecati recusandae aliquid quam', 'completed': False}, {'userId': 3, 'id': 54, 'title': 'quis et est ut voluptate quam dolor', 'completed': True}, {'userId': 3, 'id': 55, 'title': 'voluptatum omnis minima qui occaecati provident nulla voluptatem ratione', 'completed': True}, {'userId': 3, 'id': 56, 'title': 'deleniti ea temporibus enim', 'completed': True}, {'userId': 3, 'id': 57, 'title': 'pariatur et magnam ea doloribus similique voluptatem rerum quia', 'completed': False}, {'userId': 3, 'id': 58, 'title': 'est dicta totam qui explicabo doloribus qui dignissimos', 'completed': False}, {'userId': 3, 'id': 59, 'title': 'perspiciatis velit id laborum placeat iusto et aliquam odio', 'completed': False}, {'userId': 3, 'id': 60, 'title': 'et sequi qui architecto ut adipisci', 'completed': True}, {'userId': 4, 'id': 61, 'title': 'odit optio omnis qui sunt', 'completed': True}, {'userId': 4, 'id': 62, 'title': 'et placeat et tempore aspernatur sint numquam', 'completed': False}, {'userId': 4, 'id': 63, 'title': 'doloremque aut dolores quidem fuga qui nulla', 'completed': True}, {'userId': 4, 'id': 64, 'title': 'voluptas consequatur qui ut quia magnam nemo esse', 'completed': False}, {'userId': 4, 'id': 65, 'title': 'fugiat pariatur ratione ut asperiores necessitatibus magni', 'completed': False}, {'userId': 4, 'id': 66, 'title': 'rerum eum molestias autem voluptatum sit optio', 'completed': False}, {'userId': 4, 'id': 67, 'title': 'quia voluptatibus voluptatem quos similique maiores repellat', 'completed': False}, {'userId': 4, 'id': 68, 'title': 'aut id perspiciatis voluptatem iusto', 'completed': False}, {'userId': 4, 'id': 69, 'title': 'doloribus sint dolorum ab adipisci itaque dignissimos aliquam suscipit', 'completed': False}, {'userId': 4, 'id': 70, 'title': 'ut sequi accusantium et mollitia delectus sunt', 'completed': False}, {'userId': 4, 'id': 71, 'title': 'aut velit saepe ullam', 'completed': False}, {'userId': 4, 'id': 72, 'title': 'praesentium facilis facere quis harum voluptatibus voluptatem eum', 'completed': False}, {'userId': 4, 'id': 73, 'title': 'sint amet quia totam corporis qui exercitationem commodi', 'completed': True}, {'userId': 4, 'id': 74, 'title': 'expedita tempore nobis eveniet laborum maiores', 'completed': False}, {'userId': 4, 'id': 75, 'title': 'occaecati adipisci est possimus totam', 'completed': False}, {'userId': 4, 'id': 76, 'title': 'sequi dolorem sed', 'completed': True}, {'userId': 4, 'id': 77, 'title': 'maiores aut nesciunt delectus exercitationem vel assumenda eligendi at', 'completed': False}, {'userId': 4, 'id': 78, 'title': 'reiciendis est magnam amet nemo iste recusandae impedit quaerat', 'completed': False}, {'userId': 4, 'id': 79, 'title': 'eum ipsa maxime ut', 'completed': True}, {'userId': 4, 'id': 80, 'title': 'tempore molestias dolores rerum sequi voluptates ipsum consequatur', 'completed': True}, {'userId': 5, 'id': 81, 'title': 'suscipit qui totam', 'completed': True}, {'userId': 5, 'id': 82, 'title': 'voluptates eum voluptas et dicta', 'completed': False}, {'userId': 5, 'id': 83, 'title': 'quidem at rerum quis ex aut sit quam', 'completed': True}, {'userId': 5, 'id': 84, 'title': 'sunt veritatis ut voluptate', 'completed': False}, {'userId': 5, 'id': 85, 'title': 'et quia ad iste a', 'completed': True}, {'userId': 5, 'id': 86, 'title': 'incidunt ut saepe autem', 'completed': True}, {'userId': 5, 'id': 87, 'title': 'laudantium quae eligendi consequatur quia et vero autem', 'completed': True}, {'userId': 5, 'id': 88, 'title': 'vitae aut excepturi laboriosam sint aliquam et et accusantium', 'completed': False}, {'userId': 5, 'id': 89, 'title': 'sequi ut omnis et', 'completed': True}, {'userId': 5, 'id': 90, 'title': 'molestiae nisi accusantium tenetur dolorem et', 'completed': True}, {'userId': 5, 'id': 91, 'title': 'nulla quis consequatur saepe qui id expedita', 'completed': True}, {'userId': 5, 'id': 92, 'title': 'in omnis laboriosam', 'completed': True}, {'userId': 5, 'id': 93, 'title': 'odio iure consequatur molestiae quibusdam necessitatibus quia sint', 'completed': True}, {'userId': 5, 'id': 94, 'title': 'facilis modi saepe mollitia', 'completed': False}, {'userId': 5, 'id': 95, 'title': 'vel nihil et molestiae iusto assumenda nemo quo ut', 'completed': True}, {'userId': 5, 'id': 96, 'title': 'nobis suscipit ducimus enim asperiores voluptas', 'completed': False}, {'userId': 5, 'id': 97, 'title': 'dolorum laboriosam eos qui iure aliquam', 'completed': False}, {'userId': 5, 'id': 98, 'title': 'debitis accusantium ut quo facilis nihil quis sapiente necessitatibus', 'completed': True}, {'userId': 5, 'id': 99, 'title': 'neque voluptates ratione', 'completed': False}, {'userId': 5, 'id': 100, 'title': 'excepturi a et neque qui expedita vel voluptate', 'completed': False}, {'userId': 6, 'id': 101, 'title': 'explicabo enim cumque porro aperiam occaecati minima', 'completed': False}, {'userId': 6, 'id': 102, 'title': 'sed ab consequatur', 'completed': False}, {'userId': 6, 'id': 103, 'title': 'non sunt delectus illo nulla tenetur enim omnis', 'completed': False}, {'userId': 6, 'id': 104, 'title': 'excepturi non laudantium quo', 'completed': False}, {'userId': 6, 'id': 105, 'title': 'totam quia dolorem et illum repellat voluptas optio', 'completed': True}, {'userId': 6, 'id': 106, 'title': 'ad illo quis voluptatem temporibus', 'completed': True}, {'userId': 6, 'id': 107, 'title': 'praesentium facilis omnis laudantium fugit ad iusto nihil nesciunt', 'completed': False}, {'userId': 6, 'id': 108, 'title': 'a eos eaque nihil et exercitationem incidunt delectus', 'completed': True}, {'userId': 6, 'id': 109, 'title': 'autem temporibus harum quisquam in culpa', 'completed': True}, {'userId': 6, 'id': 110, 'title': 'aut aut ea corporis', 'completed': True}, {'userId': 6, 'id': 111, 'title': 'magni accusantium labore et id quis provident', 'completed': False}, {'userId': 6, 'id': 112, 'title': 'consectetur impedit quisquam qui deserunt non rerum consequuntur eius', 'completed': False}, {'userId': 6, 'id': 113, 'title': 'quia atque aliquam sunt impedit voluptatum rerum assumenda nisi', 'completed': False}, {'userId': 6, 'id': 114, 'title': 'cupiditate quos possimus corporis quisquam exercitationem beatae', 'completed': False}, {'userId': 6, 'id': 115, 'title': 'sed et ea eum', 'completed': False}, {'userId': 6, 'id': 116, 'title': 'ipsa dolores vel facilis ut', 'completed': True}, {'userId': 6, 'id': 117, 'title': 'sequi quae est et qui qui eveniet asperiores', 'completed': False}, {'userId': 6, 'id': 118, 'title': 'quia modi consequatur vero fugiat', 'completed': False}, {'userId': 6, 'id': 119, 'title': 'corporis ducimus ea perspiciatis iste', 'completed': False}, {'userId': 6, 'id': 120, 'title': 'dolorem laboriosam vel voluptas et aliquam quasi', 'completed': False}, {'userId': 7, 'id': 121, 'title': 'inventore aut nihil minima laudantium hic qui omnis', 'completed': True}, {'userId': 7, 'id': 122, 'title': 'provident aut nobis culpa', 'completed': True}, {'userId': 7, 'id': 123, 'title': 'esse et quis iste est earum aut impedit', 'completed': False}, {'userId': 7, 'id': 124, 'title': 'qui consectetur id', 'completed': False}, {'userId': 7, 'id': 125, 'title': 'aut quasi autem iste tempore illum possimus', 'completed': False}, {'userId': 7, 'id': 126, 'title': 'ut asperiores perspiciatis veniam ipsum rerum saepe', 'completed': True}, {'userId': 7, 'id': 127, 'title': 'voluptatem libero consectetur rerum ut', 'completed': True}, {'userId': 7, 'id': 128, 'title': 'eius omnis est qui voluptatem autem', 'completed': False}, {'userId': 7, 'id': 129, 'title': 'rerum culpa quis harum', 'completed': False}, {'userId': 7, 'id': 130, 'title': 'nulla aliquid eveniet harum laborum libero alias ut unde', 'completed': True}, {'userId': 7, 'id': 131, 'title': 'qui ea incidunt quis', 'completed': False}, {'userId': 7, 'id': 132, 'title': 'qui molestiae voluptatibus velit iure harum quisquam', 'completed': True}, {'userId': 7, 'id': 133, 'title': 'et labore eos enim rerum consequatur sunt', 'completed': True}, {'userId': 7, 'id': 134, 'title': 'molestiae doloribus et laborum quod ea', 'completed': False}, {'userId': 7, 'id': 135, 'title': 'facere ipsa nam eum voluptates reiciendis vero qui', 'completed': False}, {'userId': 7, 'id': 136, 'title': 'asperiores illo tempora fuga sed ut quasi adipisci', 'completed': False}, {'userId': 7, 'id': 137, 'title': 'qui sit non', 'completed': False}, {'userId': 7, 'id': 138, 'title': 'placeat minima consequatur rem qui ut', 'completed': True}, {'userId': 7, 'id': 139, 'title': 'consequatur doloribus id possimus voluptas a voluptatem', 'completed': False}, {'userId': 7, 'id': 140, 'title': 'aut consectetur in blanditiis deserunt quia sed laboriosam', 'completed': True}, {'userId': 8, 'id': 141, 'title': 'explicabo consectetur debitis voluptates quas quae culpa rerum non', 'completed': True}, {'userId': 8, 'id': 142, 'title': 'maiores accusantium architecto necessitatibus reiciendis ea aut', 'completed': True}, {'userId': 8, 'id': 143, 'title': 'eum non recusandae cupiditate animi', 'completed': False}, {'userId': 8, 'id': 144, 'title': 'ut eum exercitationem sint', 'completed': False}, {'userId': 8, 'id': 145, 'title': 'beatae qui ullam incidunt voluptatem non nisi aliquam', 'completed': False}, {'userId': 8, 'id': 146, 'title': 'molestiae suscipit ratione nihil odio libero impedit vero totam', 'completed': True}, {'userId': 8, 'id': 147, 'title': 'eum itaque quod reprehenderit et facilis dolor autem ut', 'completed': True}, {'userId': 8, 'id': 148, 'title': 'esse quas et quo quasi exercitationem', 'completed': False}, {'userId': 8, 'id': 149, 'title': 'animi voluptas quod perferendis est', 'completed': False}, {'userId': 8, 'id': 150, 'title': 'eos amet tempore laudantium fugit a', 'completed': False}, {'userId': 8, 'id': 151, 'title': 'accusamus adipisci dicta qui quo ea explicabo sed vero', 'completed': True}, {'userId': 8, 'id': 152, 'title': 'odit eligendi recusandae doloremque cumque non', 'completed': False}, {'userId': 8, 'id': 153, 'title': 'ea aperiam consequatur qui repellat eos', 'completed': False}, {'userId': 8, 'id': 154, 'title': 'rerum non ex sapiente', 'completed': True}, {'userId': 8, 'id': 155, 'title': 'voluptatem nobis consequatur et assumenda magnam', 'completed': True}, {'userId': 8, 'id': 156, 'title': 'nam quia quia nulla repellat assumenda quibusdam sit nobis', 'completed': True}, {'userId': 8, 'id': 157, 'title': 'dolorem veniam quisquam deserunt repellendus', 'completed': True}, {'userId': 8, 'id': 158, 'title': 'debitis vitae delectus et harum accusamus aut deleniti a', 'completed': True}, {'userId': 8, 'id': 159, 'title': 'debitis adipisci quibusdam aliquam sed dolore ea praesentium nobis', 'completed': True}, {'userId': 8, 'id': 160, 'title': 'et praesentium aliquam est', 'completed': False}, {'userId': 9, 'id': 161, 'title': 'ex hic consequuntur earum omnis alias ut occaecati culpa', 'completed': True}, {'userId': 9, 'id': 162, 'title': 'omnis laboriosam molestias animi sunt dolore', 'completed': True}, {'userId': 9, 'id': 163, 'title': 'natus corrupti maxime laudantium et voluptatem laboriosam odit', 'completed': False}, {'userId': 9, 'id': 164, 'title': 'reprehenderit quos aut aut consequatur est sed', 'completed': False}, {'userId': 9, 'id': 165, 'title': 'fugiat perferendis sed aut quidem', 'completed': False}, {'userId': 9, 'id': 166, 'title': 'quos quo possimus suscipit minima ut', 'completed': False}, {'userId': 9, 'id': 167, 'title': 'et quis minus quo a asperiores molestiae', 'completed': False}, {'userId': 9, 'id': 168, 'title': 'recusandae quia qui sunt libero', 'completed': False}, {'userId': 9, 'id': 169, 'title': 'ea odio perferendis officiis', 'completed': True}, {'userId': 9, 'id': 170, 'title': 'quisquam aliquam quia doloribus aut', 'completed': False}, {'userId': 9, 'id': 171, 'title': 'fugiat aut voluptatibus corrupti deleniti velit iste odio', 'completed': True}, {'userId': 9, 'id': 172, 'title': 'et provident amet rerum consectetur et voluptatum', 'completed': False}, {'userId': 9, 'id': 173, 'title': 'harum ad aperiam quis', 'completed': False}, {'userId': 9, 'id': 174, 'title': 'similique aut quo', 'completed': False}, {'userId': 9, 'id': 175, 'title': 'laudantium eius officia perferendis provident perspiciatis asperiores', 'completed': True}, {'userId': 9, 'id': 176, 'title': 'magni soluta corrupti ut maiores rem quidem', 'completed': False}, {'userId': 9, 'id': 177, 'title': 'et placeat temporibus voluptas est tempora quos quibusdam', 'completed': False}, {'userId': 9, 'id': 178, 'title': 'nesciunt itaque commodi tempore', 'completed': True}, {'userId': 9, 'id': 179, 'title': 'omnis consequuntur cupiditate impedit itaque ipsam quo', 'completed': True}, {'userId': 9, 'id': 180, 'title': 'debitis nisi et dolorem repellat et', 'completed': True}, {'userId': 10, 'id': 181, 'title': 'ut cupiditate sequi aliquam fuga maiores', 'completed': False}, {'userId': 10, 'id': 182, 'title': 'inventore saepe cumque et aut illum enim', 'completed': True}, {'userId': 10, 'id': 183, 'title': 'omnis nulla eum aliquam distinctio', 'completed': True}, {'userId': 10, 'id': 184, 'title': 'molestias modi perferendis perspiciatis', 'completed': False}, {'userId': 10, 'id': 185, 'title': 'voluptates dignissimos sed doloribus animi quaerat aut', 'completed': False}, {'userId': 10, 'id': 186, 'title': 'explicabo odio est et', 'completed': False}, {'userId': 10, 'id': 187, 'title': 'consequuntur animi possimus', 'completed': False}, {'userId': 10, 'id': 188, 'title': 'vel non beatae est', 'completed': True}, {'userId': 10, 'id': 189, 'title': 'culpa eius et voluptatem et', 'completed': True}, {'userId': 10, 'id': 190, 'title': 'accusamus sint iusto et voluptatem exercitationem', 'completed': True}, {'userId': 10, 'id': 191, 'title': 'temporibus atque distinctio omnis eius impedit tempore molestias pariatur', 'completed': True}, {'userId': 10, 'id': 192, 'title': 'ut quas possimus exercitationem sint voluptates', 'completed': False}, {'userId': 10, 'id': 193, 'title': 'rerum debitis voluptatem qui eveniet tempora distinctio a', 'completed': True}, {'userId': 10, 'id': 194, 'title': 'sed ut vero sit molestiae', 'completed': False}, {'userId': 10, 'id': 195, 'title': 'rerum ex veniam mollitia voluptatibus pariatur', 'completed': True}, {'userId': 10, 'id': 196, 'title': 'consequuntur aut ut fugit similique', 'completed': True}, {'userId': 10, 'id': 197, 'title': 'dignissimos quo nobis earum saepe', 'completed': True}, {'userId': 10, 'id': 198, 'title': 'quis eius est sint explicabo', 'completed': True}, {'userId': 10, 'id': 199, 'title': 'numquam repellendus a magnam', 'completed': True}, {'userId': 10, 'id': 200, 'title': 'ipsam aperiam voluptates qui', 'completed': False}]

In [102]:
#https://datos.gob.es/sites/default/files/u322/apis-es.pdf
# https://www.ine.es/dyngs/DataLab/manual.html?cid=1259945947373
#https://www.ine.es/jaxiT3/Tabla.htm?t=2855&L=0
response = requests.get("https://servicios.ine.es/wstempus/js/ES/DATOS_SERIE/DPOP160?nult=12")
response
json.loads(response.text)

{'COD': 'DPOP160',
 'Nombre': 'Albacete. Total. Total habitantes. Personas. ',
 'FK_Unidad': 3,
 'FK_Escala': 1,
 'Data': [{'Fecha': 1325372400000,
   'FK_TipoDato': 1,
   'FK_Periodo': 28,
   'Anyo': 2012,
   'Valor': 402837.0,
   'Secreto': False},
  {'Fecha': 1356994800000,
   'FK_TipoDato': 1,
   'FK_Periodo': 28,
   'Anyo': 2013,
   'Valor': 400007.0,
   'Secreto': False},
  {'Fecha': 1388530800000,
   'FK_TipoDato': 1,
   'FK_Periodo': 28,
   'Anyo': 2014,
   'Valor': 396987.0,
   'Secreto': False},
  {'Fecha': 1420066800000,
   'FK_TipoDato': 1,
   'FK_Periodo': 28,
   'Anyo': 2015,
   'Valor': 394580.0,
   'Secreto': False},
  {'Fecha': 1451602800000,
   'FK_TipoDato': 1,
   'FK_Periodo': 28,
   'Anyo': 2016,
   'Valor': 392118.0,
   'Secreto': False},
  {'Fecha': 1483225200000,
   'FK_TipoDato': 1,
   'FK_Periodo': 28,
   'Anyo': 2017,
   'Valor': 390032.0,
   'Secreto': False},
  {'Fecha': 1514761200000,
   'FK_TipoDato': 1,
   'FK_Periodo': 28,
   'Anyo': 2018,
   'Valor': 388786.0,
   'Secreto': False},
  {'Fecha': 1546297200000,
   'FK_TipoDato': 1,
   'FK_Periodo': 28,
   'Anyo': 2019,
   'Valor': 388167.0,
   'Secreto': False},
  {'Fecha': 1577833200000,
   'FK_TipoDato': 1,
   'FK_Periodo': 28,
   'Anyo': 2020,
   'Valor': 388270.0,
   'Secreto': False},
  {'Fecha': 1609455600000,
   'FK_TipoDato': 1,
   'FK_Periodo': 28,
   'Anyo': 2021,
   'Valor': 386464.0,
   'Secreto': False},
  {'Fecha': 1640991600000,
   'FK_TipoDato': 1,
   'FK_Periodo': 28,
   'Anyo': 2022,
   'Valor': 385727.0,
   'Secreto': False},
  {'Fecha': 1672527600000,
   'FK_TipoDato': 1,
   'FK_Periodo': 28,
   'Anyo': 2023,
   'Valor': 387174.0,
   'Secreto': False}]}

In [103]:
df = pd.DataFrame(json.loads(response.text)['Data'])
df['Fecha'] = pd.to_datetime(df['Fecha'] * 1_000_000)
df

                 Fecha  FK_TipoDato  FK_Periodo  Anyo     Valor  Secreto
0  2011-12-31 23:00:00            1          28  2012  402837.0    False
1  2012-12-31 23:00:00            1          28  2013  400007.0    False
2  2013-12-31 23:00:00            1          28  2014  396987.0    False
3  2014-12-31 23:00:00            1          28  2015  394580.0    False
4  2015-12-31 23:00:00            1          28  2016  392118.0    False
5  2016-12-31 23:00:00            1          28  2017  390032.0    False
6  2017-12-31 23:00:00            1          28  2018  388786.0    False
7  2018-12-31 23:00:00            1          28  2019  388167.0    False
8  2019-12-31 23:00:00            1          28  2020  388270.0    False
9  2020-12-31 23:00:00            1          28  2021  386464.0    False
10 2021-12-31 23:00:00            1          28  2022  385727.0    False
11 2022-12-31 23:00:00            1          28  2023  387174.0    False

                 Fecha  FK_TipoDato  FK_Periodo  Anyo    Valor  Secreto
0  2072-01-01 22:00:00            1          19  2021  22860.7    False
1  2072-06-29 20:00:00            1          20  2021  23215.5    False
2  2072-12-28 20:00:00            1          21  2021  23447.7    False
3  2073-06-30 20:00:00            1          22  2021  23288.8    False
4  2073-12-31 22:00:00            1          19  2022  23259.4    False
5  2074-06-29 20:00:00            1          20  2022  23387.4    False
6  2074-12-28 20:00:00            1          21  2022  23525.9    False
7  2075-06-30 20:00:00            1          22  2022  23487.8    False
8  2075-12-31 22:00:00            1          19  2023  23580.5    False
9  2076-06-28 20:00:00            1          20  2023  23819.2    False
10 2076-12-27 20:00:00            1          21  2023  24121.0    False
11 2077-06-29 20:00:00            1          22  2023  24077.4    False

In [104]:
response = requests.get("https://servicios.ine.es/wstempus/js/ES/DATOS_SERIE/EPA88?nult=12")
response
json.loads(response.text)

{'COD': 'EPA88',
 'Nombre': 'Total Nacional. Ambos sexos. 16 y más años. Activos. Personas. ',
 'FK_Unidad': 3,
 'FK_Escala': 4,
 'Data': [{'Fecha': 1609455600000,
   'FK_TipoDato': 1,
   'FK_Periodo': 19,
   'Anyo': 2021,
   'Valor': 22860.7,
   'Secreto': False},
  {'Fecha': 1617228000000,
   'FK_TipoDato': 1,
   'FK_Periodo': 20,
   'Anyo': 2021,
   'Valor': 23215.5,
   'Secreto': False},
  {'Fecha': 1625090400000,
   'FK_TipoDato': 1,
   'FK_Periodo': 21,
   'Anyo': 2021,
   'Valor': 23447.7,
   'Secreto': False},
  {'Fecha': 1633039200000,
   'FK_TipoDato': 1,
   'FK_Periodo': 22,
   'Anyo': 2021,
   'Valor': 23288.8,
   'Secreto': False},
  {'Fecha': 1640991600000,
   'FK_TipoDato': 1,
   'FK_Periodo': 19,
   'Anyo': 2022,
   'Valor': 23259.4,
   'Secreto': False},
  {'Fecha': 1648764000000,
   'FK_TipoDato': 1,
   'FK_Periodo': 20,
   'Anyo': 2022,
   'Valor': 23387.4,
   'Secreto': False},
  {'Fecha': 1656626400000,
   'FK_TipoDato': 1,
   'FK_Periodo': 21,
   'Anyo': 2022,
   'Valor': 23525.9,
   'Secreto': False},
  {'Fecha': 1664575200000,
   'FK_TipoDato': 1,
   'FK_Periodo': 22,
   'Anyo': 2022,
   'Valor': 23487.8,
   'Secreto': False},
  {'Fecha': 1672527600000,
   'FK_TipoDato': 1,
   'FK_Periodo': 19,
   'Anyo': 2023,
   'Valor': 23580.5,
   'Secreto': False},
  {'Fecha': 1680300000000,
   'FK_TipoDato': 1,
   'FK_Periodo': 20,
   'Anyo': 2023,
   'Valor': 23819.2,
   'Secreto': False},
  {'Fecha': 1688162400000,
   'FK_TipoDato': 1,
   'FK_Periodo': 21,
   'Anyo': 2023,
   'Valor': 24121.0,
   'Secreto': False},
  {'Fecha': 1696111200000,
   'FK_TipoDato': 1,
   'FK_Periodo': 22,
   'Anyo': 2023,
   'Valor': 24077.4,
   'Secreto': False}]}

In [106]:
df = pd.DataFrame(json.loads(response.text)['Data'])
df['Fecha'] = pd.to_datetime(df['Fecha'] * 1_000_000)

In [108]:
df

                 Fecha  FK_TipoDato  FK_Periodo  Anyo    Valor  Secreto
0  2020-12-31 23:00:00            1          19  2021  22860.7    False
1  2021-03-31 22:00:00            1          20  2021  23215.5    False
2  2021-06-30 22:00:00            1          21  2021  23447.7    False
3  2021-09-30 22:00:00            1          22  2021  23288.8    False
4  2021-12-31 23:00:00            1          19  2022  23259.4    False
5  2022-03-31 22:00:00            1          20  2022  23387.4    False
6  2022-06-30 22:00:00            1          21  2022  23525.9    False
7  2022-09-30 22:00:00            1          22  2022  23487.8    False
8  2022-12-31 23:00:00            1          19  2023  23580.5    False
9  2023-03-31 22:00:00            1          20  2023  23819.2    False
10 2023-06-30 22:00:00            1          21  2023  24121.0    False
11 2023-09-30 22:00:00            1          22  2023  24077.4    False

La variable response contendrá la respuesta HTTP, incluyendo el código de estado y los datos devueltos por la API. Puedes verificar el código de estado con response.status_code y acceder a los datos de la respuesta con response.json() si la API devuelve datos en formato JSON.

Una vez que hayas obtenido los datos de la API, es posible que desees manipularlos, analizarlos o almacenarlos en un formato estructurado. Pandas es una biblioteca popular de Python para el análisis y la manipulación de datos.

Supongamos que la API devuelve datos en formato JSON con una estructura similar a esta:

```
  {"datos": [
    {"id": 1, "nombre": "Juan", "edad": 33},
    {"id": 2, "nombre": "Carla", "edad": 23},
    {"id": 3, "nombre": "Manuel", "edad": 57}
  ]}
```

Después de realizar la solicitud y obtener la respuesta en formato JSON, puedes convertir los datos en un DataFrame de Pandas:

In [ ]:
df = pd.DataFrame(json.loads(response.text)['Data'])

--------------

## Ejemplo Practico:

### POKEAPI

Para este ejmeplo vamos a utilizar la API [POKEAPI](https://pokeapi.co/)

Lo primero que tenemos que hacer antes de `"atacar"` una API es leer la documentacion para saber que parametros utiliza y que informacion puedo obtener

Ya leido la documentacion podemos empezar a `"atacar"` la API para crear una DataFrame y poder hacer nuestro analisis de datos

Lo podemos dividir en 4 pasos:

Pado 1: Obtener nombres e ID de Pokémon y guardar en DataFrame

In [111]:
import requests
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [116]:
# Paso 1: Obtener la lista de todos los Pokémon
url = "https://pokeapi.co/api/v2/pokemon?limit=9"
response = requests.get(url)
data = response.json()

# Crear una lista de diccionarios con el nombre y la URL de cada Pokémon
pokemon_list = [{"name": pokemon["name"], "url": pokemon["url"]} for pokemon in data["results"]]

pokemon_df = pd.DataFrame(pokemon_list)
pokemon_df

         name                                   url
0   bulbasaur  https://pokeapi.co/api/v2/pokemon/1/
1     ivysaur  https://pokeapi.co/api/v2/pokemon/2/
2    venusaur  https://pokeapi.co/api/v2/pokemon/3/
3  charmander  https://pokeapi.co/api/v2/pokemon/4/
4  charmeleon  https://pokeapi.co/api/v2/pokemon/5/
5   charizard  https://pokeapi.co/api/v2/pokemon/6/
6    squirtle  https://pokeapi.co/api/v2/pokemon/7/
7   wartortle  https://pokeapi.co/api/v2/pokemon/8/
8   blastoise  https://pokeapi.co/api/v2/pokemon/9/

Esta parte del código crea un DataFrame con los nombres e ID de los Pokémon.

Paso 2: Extraer tipos y habilidades de cada Pokémon y agregarlos al DataFrame

In [117]:
#https://pokeapi.co/api/v2/pokemon/1/
def get_pokemon_details(pokemon_url):
    response = requests.get(pokemon_url)
    pokemon_data = response.json()
     
    types = [t["type"]["name"] for t in pokemon_data["types"]]
    abilities = [a["ability"]["name"] for a in pokemon_data["abilities"]]
    
    return types, abilities

pokemon_df["types"] = None
pokemon_df["abilities"] = None

for index, row in pokemon_df.iterrows():
    pokemon_url = row["url"]
    types, abilities = get_pokemon_details(pokemon_url)
    
    pokemon_df.at[index, "types"] = ", ".join(types)
    pokemon_df.at[index, "abilities"] = ", ".join(abilities)

pokemon_df.head()

,name,url,types,abilities
0,bulbasaur,https://pokeapi.co/api/v2/pokemon/1/,"grass, poison","overgrow, chlorophyll"
1,ivysaur,https://pokeapi.co/api/v2/pokemon/2/,"grass, poison","overgrow, chlorophyll"
2,venusaur,https://pokeapi.co/api/v2/pokemon/3/,"grass, poison","overgrow, chlorophyll"
3,charmander,https://pokeapi.co/api/v2/pokemon/4/,fire,"blaze, solar-power"
4,charmeleon,https://pokeapi.co/api/v2/pokemon/5/,fire,"blaze, solar-power"

Esta parte del código agrega las columnas 'types' y 'abilities' al DataFrame existente y llena cada fila con la información correspondiente.

Paso 3: Extraer estadísticas base de cada Pokémon y agregarlas al DataFrame

In [119]:
def get_base_stats(pokemon_data):
    base_stats = {}
    
    for stat in pokemon_data["stats"]:
        stat_name = stat["stat"]["name"]
        base_value = stat["base_stat"]
        base_stats[stat_name] = base_value
    
    return base_stats

stat_columns = ["hp", "attack", "defense", "special-attack", "special-defense", "speed"]

for column in stat_columns:
    pokemon_df[column] = None

for index, row in pokemon_df.iterrows():
    pokemon_url = row["url"]
    response = requests.get(pokemon_url)
    pokemon_data = response.json()
    
    base_stats = get_base_stats(pokemon_data)
    
    for stat, value in base_stats.items():
        pokemon_df.at[index, stat] = value

pokemon_df

,name,url,types,abilities,hp,attack,defense,special-attack,special-defense,speed
0,bulbasaur,https://pokeapi.co/api/v2/pokemon/1/,"grass, poison","overgrow, chlorophyll",45,49,49,65,65,45
1,ivysaur,https://pokeapi.co/api/v2/pokemon/2/,"grass, poison","overgrow, chlorophyll",60,62,63,80,80,60
2,venusaur,https://pokeapi.co/api/v2/pokemon/3/,"grass, poison","overgrow, chlorophyll",80,82,83,100,100,80
3,charmander,https://pokeapi.co/api/v2/pokemon/4/,fire,"blaze, solar-power",39,52,43,60,50,65
4,charmeleon,https://pokeapi.co/api/v2/pokemon/5/,fire,"blaze, solar-power",58,64,58,80,65,80
5,charizard,https://pokeapi.co/api/v2/pokemon/6/,"fire, flying","blaze, solar-power",78,84,78,109,85,100
6,squirtle,https://pokeapi.co/api/v2/pokemon/7/,water,"torrent, rain-dish",44,48,65,50,64,43
7,wartortle,https://pokeapi.co/api/v2/pokemon/8/,water,"torrent, rain-dish",59,63,80,65,80,58
8,blastoise,https://pokeapi.co/api/v2/pokemon/9/,water,"torrent, rain-dish",79,83,100,85,105,78

In [120]:
def get_species_details(species_data):
    is_legendary = species_data["is_legendary"]
    generation = species_data["generation"]["name"]
    return is_legendary, generation

def get_hidden_ability(pokemon_data):
    hidden_ability = None
    for ability in pokemon_data["abilities"]:
        if ability["is_hidden"]:
            hidden_ability = ability["ability"]["name"]
            break
    return hidden_ability

def get_primary_type(pokemon_data):
    primary_type = pokemon_data["types"][0]["type"]["name"]
    return primary_type

def get_weight_and_height(pokemon_data):
    weight = pokemon_data["weight"]
    height = pokemon_data["height"]
    return weight, height


# Agregar las columnas 'is_legendary', 'generation', 'hidden_ability' y 'primary_type' al DataFrame
pokemon_df["is_legendary"] = None
pokemon_df["generation"] = None
pokemon_df["hidden_ability"] = None
pokemon_df["primary_type"] = None
pokemon_df["weight"] = None
pokemon_df["height"] = None

# Completar las columnas 'is_legendary', 'generation', 'hidden_ability' y 'primary_type' con los valores reales
for index, row in pokemon_df.iterrows():
    pokemon_url = row["url"]
    response = requests.get(pokemon_url)
    pokemon_data = response.json()
    
    species_url = pokemon_data["species"]["url"]
    species_response = requests.get(species_url)
    species_data = species_response.json()
    
    is_legendary, generation = get_species_details(species_data)
    hidden_ability = get_hidden_ability(pokemon_data)
    primary_type = get_primary_type(pokemon_data)
    weight, height = get_weight_and_height(pokemon_data)
    
    pokemon_df.at[index, "is_legendary"] = is_legendary
    pokemon_df.at[index, "generation"] = generation
    pokemon_df.at[index, "hidden_ability"] = hidden_ability
    pokemon_df.at[index, "primary_type"] = primary_type
    pokemon_df.at[index, "weight"] = weight
    pokemon_df.at[index, "height"] = height

pokemon_df

,name,url,types,abilities,hp,attack,defense,special-attack,special-defense,speed,is_legendary,generation,hidden_ability,primary_type,weight,height
0,bulbasaur,https://pokeapi.co/api/v2/pokemon/1/,"grass, poison","overgrow, chlorophyll",45,49,49,65,65,45,False,generation-i,chlorophyll,grass,69,7
1,ivysaur,https://pokeapi.co/api/v2/pokemon/2/,"grass, poison","overgrow, chlorophyll",60,62,63,80,80,60,False,generation-i,chlorophyll,grass,130,10
2,venusaur,https://pokeapi.co/api/v2/pokemon/3/,"grass, poison","overgrow, chlorophyll",80,82,83,100,100,80,False,generation-i,chlorophyll,grass,1000,20
3,charmander,https://pokeapi.co/api/v2/pokemon/4/,fire,"blaze, solar-power",39,52,43,60,50,65,False,generation-i,solar-power,fire,85,6
4,charmeleon,https://pokeapi.co/api/v2/pokemon/5/,fire,"blaze, solar-power",58,64,58,80,65,80,False,generation-i,solar-power,fire,190,11
5,charizard,https://pokeapi.co/api/v2/pokemon/6/,"fire, flying","blaze, solar-power",78,84,78,109,85,100,False,generation-i,solar-power,fire,905,17
6,squirtle,https://pokeapi.co/api/v2/pokemon/7/,water,"torrent, rain-dish",44,48,65,50,64,43,False,generation-i,rain-dish,water,90,5
7,wartortle,https://pokeapi.co/api/v2/pokemon/8/,water,"torrent, rain-dish",59,63,80,65,80,58,False,generation-i,rain-dish,water,225,10
8,blastoise,https://pokeapi.co/api/v2/pokemon/9/,water,"torrent, rain-dish",79,83,100,85,105,78,False,generation-i,rain-dish,water,855,16

Esta parte del código agrega las columnas de estadísticas base al DataFrame existente y llena cada fila con la información correspondiente.

Paso 4: Guardar el DataFrame en un archivo CSV

In [121]:
# Guardar el DataFrame en un archivo CSV
csv_output_file = "pokemon_data.csv"
pokemon_df.to_csv(csv_output_file, index=False)
print(f"Archivo CSV guardado como: {csv_output_file}")

Archivo CSV guardado como: pokemon_data.csv